import { auth } from '@/config/firebase';
import { signOut } from 'firebase/auth';
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  const logout = async () => {
    try {
      await signOut(auth);
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <>
      <Head>
        <title>BB Kids Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <main>
        Link to: <Link href="/posts/first-post"> Post</Link>
        <button onClick={logout}>Logout</button>
      </main>
    </>
  )
}
